crowbar-backup: Verify that install-suse-cloud finished successfully
It doesn't make sense to continue if install-suse-cloud failed.

diff --git a/backup/crowbar-backup b/backup/crowbar-backup
--- a/backup/crowbar-backup
+++ b/backup/crowbar-backup
@@ -214,9 +214,11 @@ function restore()
 
   # calling install-suse-cloud script
   echo "Waiting for install-suse-cloud to finish:"
-  # copied from qa_crowbarsetup
+  pushd /root  > /dev/null
   screen -d -m -L /bin/bash -c "rm -f /tmp/chef-ready ; install-suse-cloud --verbose ; touch /tmp/chef-ready"
   sleep 2 # need to wait for initial deletion of chef-ready
+  popd > /dev/null
+
   n=300
   while [ $n -gt 0 ] && [ ! -e /tmp/chef-ready ] ; do
     n=$(expr $n - 1)
@@ -228,6 +230,13 @@ function restore()
     exit 83
   fi
   echo
+
+  # Make sure install finished correctly
+  if ! [ -e /opt/dell/crowbar_framework/.crowbar-installed-ok ]; then
+    echo "Crowbar \".crowbar-installed-ok\" marker missing"
+    tail -n 90 /root/screenlog.0
+    exit 89
+  fi
 
   # restoring files and reconfiguring services
   rccouchdb stop
