Remove ping test (bnc#901744)
Some environments do not allow to send pings. The real point of the
code was to check if DNS resolution is working. So just do a DNS
test.

diff --git a/backup/crowbar-backup b/backup/crowbar-backup
--- a/backup/crowbar-backup
+++ b/backup/crowbar-backup
@@ -50,7 +50,7 @@ done
 
 # _domainname_ of a server for a ping and DNS test
 # can be set via "export pingserver=ping.example.com"
-PINGSERVER=${pingserver:-turing.suse.de}
+HOSTTEST=${pingserver:-www.suse.com}
 
 # default backup file name
 FILEDEF=/tmp/backup-crowbar.tar.gz
@@ -92,8 +92,8 @@ function check_resolv_conf
       echo "Error: Nameserver '$ns' is not available. Please reconfigure /etc/resolv.conf manually."
       exit 1
     fi
-    if ! ping -c1 "$PINGSERVER" ; then
-      echo "Error: Nameserver '$ns' can not resolve or ping $PINGSERVER. Please reconfigure /etc/resolv.conf manually"
+    if ! getent hosts "$HOSTTEST" >/dev/null; then
+      echo "Error: Nameserver '$ns' can not resolve or ping $HOSTTEST. Please reconfigure /etc/resolv.conf manually"
       exit 1
     fi
   done
